### PR TITLE
Add options to match start or end of input

### PR DESCRIPTION
**Pull request by akonsu**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? What's your use-case?

**Comment by akonsu** [comment]
I use this regex in a call to Codemirror's `stream.match` API (https://codemirror.net/doc/manual.html#modeapi) It requires that the pattern has starting anchor `^` so that it can match a token at the beginning of the stream.

**Comment by sindresorhus** [comment]
Sorry about the delay. Alright. Will merge if you add a couple of tests ;)

**Comment by sindresorhus** [comment]
Ping @akonsu :)

**Comment by sindresorhus** [comment]
Closing for lack of response.

**Comment by kevva** [comment]
Another way is to just wrap it:

```js
const regex = new RegExp(`^${emailRegex().source}`);

regex.match('unicorn hello@example.com');
//=> false

regex.match('hello@example.com');
//=> true
```

**Pull request closed without merging**
